name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: write   # precisa de write para commitar o SVG

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # Para conseguir fazer commit

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: juaosea
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          config_octicon: true
          config_timezone: America/Sao Paulo
          config_twemoji: true
          plugin_languages: true
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: true
          plugin_languages_limit: 8
          plugin_languages_other: true
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_leetcode: true
          plugin_leetcode_limit_recent: 2
          plugin_leetcode_limit_skills: 10
          plugin_leetcode_sections: solved
          plugin_leetcode_user: juaosea
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}

      - name: Commit and Push Metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📈 Update GitHub metrics [skip ci]"
          branch: main
          file_pattern: 'github-metrics.svg'
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
